/**
 * pdf-export.js
 * -------------
 * Turns any of the tool results (symptom checker, BMI, skin screening,
 * blood report) into a downloadable PDF summary via jsPDF. Reads the
 * `last*Result` variables set by each feature module.
 */

function getJsPDF() {
  return window.jspdf && window.jspdf.jsPDF ? window.jspdf.jsPDF : null;
}

function buildPdf(title, rows) {
  const JsPDFCtor = getJsPDF();
  if (!JsPDFCtor) {
    toast('PDF library did not load — check your connection and try again.', 'error');
    return null;
  }

  const doc = new JsPDFCtor({ unit: 'pt', format: 'a4' });
  const marginX = 48;
  let y = 64;

  doc.setFillColor(6, 182, 212);
  doc.rect(0, 0, 595, 60, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text('AarogyaAI — Health Summary', marginX, 38);

  doc.setTextColor(20, 20, 30);
  y = 90;
  doc.setFontSize(14);
  doc.text(title, marginX, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(marginX, y, 547, y);
  y += 26;

  doc.setFontSize(11);
  rows.forEach(([label, value]) => {
    doc.setFont(undefined, 'bold');
    doc.text(label + ':', marginX, y);
    doc.setFont(undefined, 'normal');

    const lines = doc.splitTextToSize(String(value == null ? '—' : value), 400);
    doc.text(lines, marginX + 150, y);
    y += Math.max(18, lines.length * 14 + 4);

    if (y > 760) {
      doc.addPage();
      y = 60;
    }
  });

  y += 10;
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  const disclaimer = doc.splitTextToSize(
    `Generated by AarogyaAI for reference only. This is general AI-assisted guidance, not a medical diagnosis. Please consult a qualified doctor for confirmation and treatment. Date: ${new Date().toLocaleString()}`,
    500
  );
  doc.text(disclaimer, marginX, y);

  return doc;
}

document.getElementById('download-symptom-pdf').addEventListener('click', () => {
  if (!lastSymptomResult) {
    toast('Run the symptom checker first.', 'warn');
    return;
  }
  const doc = buildPdf('Symptom Checker Result', [
    ['Possible Condition', lastSymptomResult.possible_condition],
    ['Risk Level', lastSymptomResult.risk_level],
    ['Recommended Doctor', lastSymptomResult.recommended_doctor],
    ['AI Guidance', lastSymptomResult.guidance]
  ]);
  if (doc) doc.save('AarogyaAI_Symptom_Summary.pdf');
});

document.getElementById('download-bmi-pdf').addEventListener('click', () => {
  if (!lastBmiResult) {
    toast('Calculate your BMI first.', 'warn');
    return;
  }
  const doc = buildPdf('BMI Report', [
    ['BMI', lastBmiResult.bmi],
    ['Category', lastBmiResult.category],
    ['Advice', lastBmiResult.advice]
  ]);
  if (doc) doc.save('AarogyaAI_BMI_Summary.pdf');
});

document.getElementById('download-skin-pdf').addEventListener('click', () => {
  if (!lastSkinResult) {
    toast('Run a skin screening first.', 'warn');
    return;
  }
  const doc = buildPdf('Skin Screening Result', [
    ['Observation', lastSkinResult.prediction],
    ['Severity', lastSkinResult.severity],
    ['Possible Cause', lastSkinResult.causes],
    ['Recommendation', lastSkinResult.recommendation],
    ['Suggested Specialist', lastSkinResult.doctor]
  ]);
  if (doc) doc.save('AarogyaAI_Skin_Summary.pdf');
});

document.getElementById('download-report-pdf').addEventListener('click', () => {
  if (!lastReportResult) {
    toast('Analyze a report first.', 'warn');
    return;
  }
  const doc = buildPdf('Blood Report Analysis', [
    ['Hemoglobin', lastReportResult.hemoglobin + ' g/dL'],
    ['Fasting Blood Sugar', lastReportResult.blood_sugar + ' mg/dL'],
    ['Cholesterol', lastReportResult.cholesterol + ' mg/dL'],
    ['Overall Risk', lastReportResult.risk],
    ['Summary', lastReportResult.summary]
  ]);
  if (doc) doc.save('AarogyaAI_Report_Summary.pdf');
});
